version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: crudify-db
    environment:
      POSTGRES_DB: crudify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crudify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: ./crudify-server
      dockerfile: Dockerfile
    container_name: crudify-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/crudify_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - crudify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/products"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: ./crudify-client
      dockerfile: Dockerfile
    container_name: crudify-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - crudify-network

volumes:
  postgres_data:

networks:
  crudify-network:
    driver: bridge 